config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("messaging/admin/", admin.site.urls),
    path("", include("message_sending.urls", namespace="messaging")),
    path("users/", include("users.urls", namespace="users")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message_sending/urls.py
from django.urls import path

from message_sending.apps import MessageSendingConfig
from message_sending.views import (AddresseeCreateView, AddresseeDeleteView,
                                   AddresseeDetailView, AddresseeListView,
                                   AddresseeUpdateView, LogListView,
                                   MailingCreateView, MailingDeleteView,
                                   MailingDetailView, MailingListView,
                                   MailingStatusView, MailingUpdateView,
                                   MessageCreateView, MessageDeleteView,
                                   MessageDetailView, MessageListView,
                                   MessageUpdateView, SampleView,
                                   mailing_send_view)

# from django.views.decorators.cache import cache_page


app_name = MessageSendingConfig.name

urlpatterns = [
    path("", SampleView.as_view(), name="main"),
    path("create_addressee/", AddresseeCreateView.as_view(), name="addressee_create"),
    path("create_message/", MessageCreateView.as_view(), name="message_create"),
    path("create_mailing/", MailingCreateView.as_view(), name="mailing_create"),
    path(
        "addressee/<int:pk>/update/",
        AddresseeUpdateView.as_view(),
        name="addressee_update",
    ),
    path("addressee_list/", AddresseeListView.as_view(), name="addressee_list"),
    path("addressee/<int:pk>", AddresseeDetailView.as_view(), name="addressee_detail"),
    path(
        "addressee/<int:pk>/delete/",
        AddresseeDeleteView.as_view(),
        name="addressee_delete",
    ),
    path(
        "message/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"
    ),
    path("message_list/", MessageListView.as_view(), name="message_list"),
    path("message/<int:pk>", MessageDetailView.as_view(), name="message_detail"),
    path(
        "message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path(
        "mailing/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"
    ),
    path("mailing_list/", MailingListView.as_view(), name="mailing_list"),
    path("mailing/<int:pk>", MailingDetailView.as_view(), name="mailing_detail"),
    path(
        "mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"
    ),
    path("log_list/", LogListView.as_view(), name="log_list"),
    path("mailing/<int:pk>/send/", mailing_send_view, name="mailing_send"),
    path(
        "mailing/<int:pk>/unacivate/",
        MailingStatusView.as_view(),
        name="mailing_unactivate",
    ),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (BlockUsersView, UserCreateView, UserDetailView,
                         UserForgotPasswordView, UserListView,
                         UserPasswordResetConfirmView, UserUpdateView)

app_name = UsersConfig.name

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(template_name="login.html", next_page="messaging:main"),
        name="login",
    ),
    path("logout/", LogoutView.as_view(next_page="messaging:main"), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("user/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("user/<int:pk>/update/", UserUpdateView.as_view(), name="user_update"),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path(
        "set-new-password/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("user/<int:pk>/block", BlockUsersView.as_view(), name="user_block"),
]

message_sending/models.py
from django.db import models

from users.models import User


class Addressee(models.Model):
    email = models.CharField(
        max_length=100,
        verbose_name="E-mail адрес",
        help_text="Введите e-mail",
        unique=True,
    )
    name = models.CharField(
        max_length=150, verbose_name="Фамилия Имя Отчество", help_text="Введите Ф.И.О."
    )
    comment = models.TextField(
        null=True,
        blank=True,
        verbose_name="Комментарий",
        help_text="Введите комментарий",
    )
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец",
        help_text="Введите владельца продукта",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "адресат"
        verbose_name_plural = "адресаты"
        ordering = ["email", "name"]
        permissions = [
            ("can_view_addressees", "Can view addressees"),
        ]


class Message(models.Model):
    subject = models.CharField(
        max_length=100, verbose_name="Тема письма", help_text="Введите тему письма"
    )
    body = models.TextField(verbose_name="Тело письма", help_text="Введите текст")
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец",
        help_text="Введите владельца продукта",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = "сообщение"
        verbose_name_plural = "сообщения"
        ordering = ["subject"]
        permissions = [
            ("can_view_messages", "Can view messages"),
        ]


class Mailing(models.Model):
    COMPLETED = "completed"
    CREATED = "created"
    LAUNCHED = "launched"

    STATUS_CHOISES = [
        (COMPLETED, "Завершена"),
        (CREATED, "Создана"),
        (LAUNCHED, "Запущена"),
    ]

    start_mailing = models.DateField(auto_now_add=True)
    end_mailing = models.DateField(null=True, blank=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOISES, default=CREATED, verbose_name="Статус"
    )
    message = models.ForeignKey(
        Message,
        verbose_name="Сообщение",
        help_text="Введите сообщение",
        on_delete=models.CASCADE,
    )
    addressee = models.ManyToManyField(
        Addressee,
        verbose_name="Получатель",
        help_text="Введите получателя",
    )
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец",
        help_text="Введите владельца продукта",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"Сообщение: {self.message.subject}"

    class Meta:
        verbose_name = "рассылка"
        verbose_name_plural = "рассылки"
        ordering = ["status"]
        permissions = [
            ("can_view_mailings", "Can view mailings"),
            ("can_change_status", "Can change status"),
        ]


class Log(models.Model):
    SUCCESSFULL = "Successfully"
    UNSUCCESSFULL = "Unsuccessfully"

    STATUS_CHOICES = [
        (SUCCESSFULL, "Успешно"),
        (UNSUCCESSFULL, "Не успешно"),
    ]

    datetime = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default=UNSUCCESSFULL,
        verbose_name="Статус",
    )
    answer = models.TextField(verbose_name="Ответ почтового сервера")
    mailing = models.ForeignKey(
        Mailing, verbose_name="Рассылка", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"Статус попытки рассылки: {self.status}"

    class Meta:
        verbose_name = "попытка"
        verbose_name_plural = "попытки"
        ordering = ["status"]

message_sending/forms.py
from django.forms import ModelForm

from message_sending.models import Addressee, Mailing, Message


class AddresseeForm(ModelForm):
    class Meta:
        model = Addressee
        exclude = ("owner",)

    def __init__(self, *args, **kwargs):
        super(AddresseeForm, self).__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите Ф.И.О."}
        )
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите email"}
        )
        self.fields["comment"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Добавьте комментарий"}
        )


class MessageForm(ModelForm):
    class Meta:
        model = Message
        exclude = ("owner",)

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields["subject"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите тему письма"}
        )
        self.fields["body"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите информацию"}
        )


class MailingForm(ModelForm):
    class Meta:
        model = Mailing
        exclude = (
            "start_mailing",
            "end_mailing",
            "status",
            "owner",
        )

    def __init__(self, *args, **kwargs):
        super(MailingForm, self).__init__(*args, **kwargs)
        self.fields["message"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Выберите сообщение"}
        )
        self.fields["addressee"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Добавьте получателей"}
        )

message_sending/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import (DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)
from django.views.generic.edit import CreateView

from .forms import AddresseeForm, MailingForm, MessageForm
from .models import Addressee, Log, Mailing, Message
from .services.send_mail import EmailService


class AddresseeCreateView(LoginRequiredMixin, CreateView):
    model = Addressee
    form_class = AddresseeForm
    success_url = reverse_lazy("message_sending:addressee_list")

    def form_valid(self, form):
        addressee = form.save()
        user = self.request.user
        addressee.owner = user
        addressee.save()
        return super().form_valid(form)


class AddresseeUpdateView(LoginRequiredMixin, UpdateView):
    model = Addressee
    form_class = AddresseeForm
    success_url = reverse_lazy("message_sending:addressee_list")


@method_decorator(cache_page(60 * 15), name="dispatch")
class AddresseeListView(LoginRequiredMixin, ListView):
    model = Addressee
    template_name = 'message_sending/addressee_list.html'
    context_object_name = 'addressees'

    def get_queryset(self):
        user = self.request.user
        user_id = user.id
        if not self.request.user.has_perm('message_sending.can_view_addressees'):
            return Addressee.objects.filter(owner_id=user_id)
        return Addressee.objects.all()


@method_decorator(cache_page(60 * 15), name="dispatch")
class AddresseeDetailView(LoginRequiredMixin, DetailView):
    model = Addressee


class AddresseeDeleteView(LoginRequiredMixin, DeleteView):
    model = Addressee
    success_url = reverse_lazy("message_sending:addressee_list")


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("message_sending:message_list")

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("message_sending:message_list")


@method_decorator(cache_page(60 * 15), name="dispatch")
class MessageListView(ListView):
    model = Message
    context_object_name = 'messages'

    def get_queryset(self):
        user = self.request.user
        user_id = user.id
        if not self.request.user.has_perm('message_sending.can_view_messages'):
            return Message.objects.filter(owner_id=user_id)
        return Message.objects.all()


@method_decorator(cache_page(60 * 15), name="dispatch")
class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy("message_sending:message_list")


class MailingListView(ListView):
    model = Mailing
    template_name = "message_sending/mailing_list.html"
    context_object_name = 'mailings'

    def get_queryset(self):
        user = self.request.user
        user_id = user.id
        if not self.request.user.has_perm('message_sending.can_view_mailings'):
            return Mailing.objects.filter(owner_id=user_id)
        return Mailing.objects.all()


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("message_sending:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("message_sending:mailing_list")

    def post(self, request, *args, **kwargs):
        print(request.POST)
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)


class MailingDetailView(DetailView):
    model = Mailing


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy("message_sending:mailing_list")


class LogListView(LoginRequiredMixin, ListView):
    model = Log


class SampleView(TemplateView):
    model = Mailing
    template_name = "message_sending/main.html"


def mailing_send_view(request, pk):
    mailing = Mailing.objects.get(pk=pk)
    EmailService().send_message(pk)
    mailing.status = Mailing.COMPLETED
    mailing.save()
    return redirect(reverse("message_sending:mailing_list"))


class MailingStatusView(View):
    def post(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)

        if not request.user.has_perm("message_sending.can_change_status"):
            return HttpResponseForbidden("У вас нет прав для отключения рассылки.")

        mailing.is_active = False
        mailing.save()

        return redirect("message_sending:mailing_detail", pk=pk)

message_sending/templates/message_sending/addressee_confirm_delete.html
{% extends 'message_sending/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text"> Вы действительно хотите удалить {{ object.name }}? </p>
                    <div class="card-body">
                         {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-danger"> Удалить </button>
                    <a href="{% url 'messaging:main' %}" class="btn btn-primary"> Отмена </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

message_sending/templates/message_sending/addressee_detail.html
{% extends 'message_sending/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col" xmlns="http://www.w3.org/1999/html">
    <div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Наименование:</p>{{ object.name }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Ф.И.О. получателя: </p> {{ object.name }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Электронный адрес: </p> {{ object.email }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Комментарий: </p> {{ object.comment }}
                    </li>
                </ul>
            </p>

            <div class="d-flex justify-content-between align-items-center"><div class="btn-group">
                <a class="btn btn-primary" href="{% url 'message_sending:addressee_list' %}" role="button">Назад</a>
                <a class="btn btn-primary" href="{% url 'message_sending:addressee_update' object.pk %}" role="button">Редактировать</a>
                <a class="btn btn-primary" href="{% url 'message_sending:addressee_delete' object.pk %}" role="button">Удалить</a>

            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

message_sending/templates/message_sending/addressee_form.html
{% extends 'message_sending/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                         {% csrf_token %}
                         {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                     <a href="{% url 'messaging:main' %}" class="btn btn-secondary">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

message_sending/templates/message_sending/addressee_list.html
{% extends 'message_sending/base.html' %}
{% load my_tags %}
{% block content %}
<div> <a class="btn btn-primary" href="{% url 'message_sending:addressee_create' %}" role="button">Создать нового получателя</a>
                  </div>
{% for object in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">
                <h3> Ф.И.О. получателя: {{ object.name }}</h3>
                </p>
                <p class="card-text">
                <h3> Электронный адрес: {{ object.email }}</h3>
                </p>
                <p class="card-text">
                 Комментарий: {{ object.comment | truncatechars:100 }}
                </p>
               <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% if user == object.owner %}
                  <a class="btn btn-primary" href="{% url 'message_sending:addressee_detail' object.pk  %}" role="button">Перейти в карточку получателя</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
{% endfor %}
{% endblock %}

message_sending/templates/message_sending/log_list.html
{% extends 'message_sending/base.html' %}
{% load my_tags %}
{% block content %}

<h3>Всего рассылок: {% count_all %} </h3>
<h3>Успешных рассылок: {% count_successfull_mailings %} </h3>
<h3>Неуспешных рассылок: {% count_unsuccessfull_mailings %} </h3>
<h3>Отправлено писем: {% count_sent_mails %} </h3>

{% for object in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">
                <h3> Статус: {{ object.status }}</h3>
                </p>
                <p class="card-text">
                <h3> Рассылка: {{ object.mailing }}
                </h3>
                </p>
                <p class="card-text">
                <h3> Ответ: {{ object.answer }}</h3>
                </p>
            </div>
          </div>
        </div>
{% endfor %}

{% endblock %}

message_sending/templates/message_sending/mailing_confirm_delete.html
{% extends 'message_sending/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text"> Вы действительно хотите удалить {{ object.name }}? </p>
                    <div class="card-body">
                         {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-danger"> Удалить </button>
                    <a href="{% url 'messaging:mailing_list' %}" class="btn btn-primary"> Отмена </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

message_sending/templates/message_sending/mailing_form.html
{% extends 'message_sending/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                         {% csrf_token %}
                         {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                     <a href="{% url 'messaging:mailing_list' %}" class="btn btn-secondary">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

message_sending/templates/message_sending/mailing_list.html
{% extends 'message_sending/base.html' %}
{% load my_tags %}
{% block content %}
<div> <a class="btn btn-primary" href="{% url 'message_sending:mailing_create' %}" role="button">Создать новую рассылку</a>
                  </div>
{% for object in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">
                <h3> Статус: {{ object.status }}</h3>
                </p>
                <p class="card-text">
                <h3> Сообщение: {{ object.message }}
                </h3>
                </p>
                <p class="card-text">
                <h3> Получатель:
              {% for addressee in object.addressee.all %}
                        {{ addressee.email}},
                        {% endfor %}</h3>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% if "message_sending.can_view_mailings" in perms or user == object.owner %}
                  <a class="btn btn-primary" href="{% url 'message_sending:mailing_detail' object.pk  %}" role="button">Перейти в карточку рассылки</a>
                  {% if object.status != "completed" %}
                  <a class="btn btn-success" href="{% url 'message_sending:mailing_send' object.pk  %}" role="button">Начать рассылку</a>
                  {% endif %}
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
{% endfor %}
{% endblock %}

message_sending/templates/message_sending/main.html
{% extends 'message_sending/base.html' %}
{% load my_tags %}
{% block content %}
{% if "message_sending.can_change_status" in perms %}
<div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Количество всех рассылок:</p> {% count_all %}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Количество активных рассылок: </p> {% count_active_mailings %}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Количество уникальных получателей: </p> {% count_unique_addressees %}
                    </li>
                </ul>
            </p>
            </div>
        </div>
    </div>
{% else %}
<div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Количество всех рассылок:</p> {% count_all_for_user user %}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Количество активных рассылок: </p> {% count_active_mailings_for_user user %}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Количество уникальных получателей: </p> {% count_unique_addressees_for_user user %}
                    </li>
                </ul>
            </p>
            </div>
        </div>
    </div>

{% endif %}
{% endblock %}

message_sending/templates/message_sending/message_confirm_delete.html
{% extends 'message_sending/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text"> Вы действительно хотите удалить {{ object.name }}? </p>
                    <div class="card-body">
                         {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-danger"> Удалить </button>
                    <a href="{% url 'messaging:main' %}" class="btn btn-primary"> Отмена </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

message_sending/templates/message_sending/message_form.html
{% extends 'message_sending/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                         {% csrf_token %}
                         {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                     <a href="{% url 'messaging:main' %}" class="btn btn-secondary">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}