config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("messaging/admin/", admin.site.urls),
    path("", include("message_sending.urls", namespace="messaging")),
    path("users/", include("users.urls", namespace="users")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (BlockUsersView, UserCreateView, UserDetailView,
                         UserForgotPasswordView, UserListView,
                         UserPasswordResetConfirmView, UserUpdateView)

app_name = UsersConfig.name

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(template_name="login.html", next_page="messaging:main"),
        name="login",
    ),
    path("logout/", LogoutView.as_view(next_page="messaging:main"), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("user/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("user/<int:pk>/update/", UserUpdateView.as_view(), name="user_update"),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path(
        "set-new-password/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("user/<int:pk>/block", BlockUsersView.as_view(), name="user_block"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    phone = PhoneNumberField(
        verbose_name="Телефон",
        blank=True,
        null=True,
        help_text="Введите номер телефона",
    )
    country = models.CharField(
        max_length=50,
        verbose_name="Страна",
        blank=True,
        null=True,
        help_text="Введите назввание вашей страны",
    )
    avatar = models.ImageField(
        upload_to="users/avatars/",
        verbose_name="Аватар",
        blank=True,
        null=True,
        help_text="Загрузите свое фото",
    )

    token = models.CharField(
        max_length=100, verbose_name="Token", blank=True, null=True
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_view_users", "Can view users"),
            ("can_block_users", "Can block"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import (PasswordResetForm, SetPasswordForm,
                                       UserCreationForm)
from django.forms import ModelForm

from users.models import User


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ("phone", "country")


class UserForgotPasswordForm(PasswordResetForm):
    """
    Запрос на восстановление пароля
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {"class": "form-control", "autocomplete": "off"}
            )


class UserSetNewPasswordForm(SetPasswordForm):
    """
    Изменение пароля пользователя после подтверждения
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {"class": "form-control", "autocomplete": "off"}
            )

users/views.py
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.contrib.auth.views import (PasswordResetConfirmView,
                                       PasswordResetView)
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, ListView, UpdateView, View
from django.views.generic.edit import CreateView

from config.settings import EMAIL_HOST_USER
from users.forms import (UserForgotPasswordForm, UserForm,
                         UserRegistrationForm, UserSetNewPasswordForm)
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegistrationForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        self.send_welcome_email(user.email)
        return super().form_valid(form)

    @staticmethod
    def send_welcome_email(user_email):
        subject = f"Добро пожаловать, {user_email}!"
        message = "Спасибо, что зарегистрировались! Теперь Ваш аккаунт активирован"
        from_email = EMAIL_HOST_USER
        recipient_list = [user_email]
        send_mail(
            subject=subject,
            message=message,
            from_email=from_email,
            recipient_list=recipient_list,
        )


class UserUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy("message_sending:main")
    permission_required = 'users.change_user'


@method_decorator(cache_page(60 * 15), name="dispatch")
class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy("message_sending:main")
    permission_required = 'users.change_user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        return context


@method_decorator(cache_page(60 * 15), name="dispatch")
class UserListView(ListView):
    model = User


class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """
    Представление по сбросу пароля по почте
    """

    form_class = UserForgotPasswordForm
    template_name = "users/user_password_reset.html"
    success_url = reverse_lazy("message_sending:main")
    success_message = (
        "Письмо с инструкцией по восстановлению пароля отправлена на ваш email"
    )
    subject_template_name = "users/email/password_subject_reset_mail.txt"
    email_template_name = "users/email/password_reset_mail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Запрос на восстановление пароля"
        return context


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """
    Представление установки нового пароля
    """

    form_class = UserSetNewPasswordForm
    template_name = "users/user_password_set_new.html"
    success_url = reverse_lazy("users:login")
    success_message = "Пароль успешно изменен. Можете авторизоваться на сайте."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Установить новый пароль"
        return context


class BlockUsersView(LoginRequiredMixin, PermissionRequiredMixin, View):
    def post(self, request, pk):
        user = get_object_or_404(User, id=pk)

        if not request.user.has_perm("users.can_view_users"):
            return HttpResponseForbidden("У вас нет прав для блокировки пользователя.")

        user.is_active = False
        user.save()

        return redirect("users:user_detail", pk=pk)

users/templates/users/login.html
{% extends 'message_sending/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                         {% csrf_token %}
                         {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                       Войти
                    </button>
                    <a href="{% url 'users:password_reset' %}" class="btn btn-primary">Восстановить пароль</a>
                     <a href="{% url 'messaging:main' %}" class="btn btn-secondary">Отмена</a>

                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends 'message_sending/base.html' %}

{% block content %}
  <h2>Вы вышли из системы</h2>
  <p>Спасибо, что воспользовались нашим сайтом. Вы успешно вышли из системы.</p>
  <a href="{% url 'users:login' %}">Войти снова</a>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'message_sending/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col" xmlns="http://www.w3.org/1999/html">
    <div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">
            Пользователь {{ object.email }}
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Телефон:</p>{{ object.phone }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Страна: </p> {{ object.country }}
                    </li>
            <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                        <p class="fw-bold">Активен: </p> {{ object.is_active }}
                    </li>
             {% if 'users.can_block_users' in perms and user != object %}
             <form action="{% url 'users:user_block' object.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Заблокировать пользователя</button>
    </form>
{% endif %}
                </ul>
            </p>

            <div class="d-flex justify-content-between align-items-center"><div class="btn-group">
                <a class="btn btn-primary" href="{% url 'message_sending:main' %}" role="button">Назад</a>
                <a class="btn btn-primary" href="{% url 'users:user_update' object.pk %}" role="button">Редактировать</a>

            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'message_sending/base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                         {% csrf_token %}
                         {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                       Зарегистрироваться
                    </button>
                     <a href="{% url 'messaging:main' %}" class="btn btn-secondary">Отмена</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'message_sending/base.html' %}
{% load my_tags %}
{% block content %}

{% for object in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">
                <h3> Email: {{ object.email }}</h3>
                </p>
                <p class="card-text">
                <h3> Телефон: {{ object.phone }}</h3>
                </p>
                <p class="card-text">
                <h3> Страна: {{ object.country }}</h3>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% if 'users.can_block_users' in perms or user == object.owner %}
                  <a class="btn btn-primary" href="{% url 'users:user_detail' object.pk  %}" role="button">Перейти в карточку пользователя</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
{% endfor %}
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'message_sending/base.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Запрос на восстановление пароля на сайте</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Восстановить пароль</button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/user_password_set_new.html
{% extends 'message_sending/base.html' %}

{% block content %}
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Установить новый пароль</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Подтвердить</button>
            </form>
        </div>
    </div>
{% endblock %}